### ISSUE TITLE
lab needs reworking

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/devise_roles_lab#10]
This lab needs some major examination.

In `spec/features/users/user_delete_spec`, if you comment out `skip 'skip a slow test'`, the test will run, but opens a new Firefox window and times out.  Not touching that.

I truly have no idea how `spec/features/visitors/about_page_spec` is passing.  It visits `pages/about` and looks for the text "About the Website", but it's nowhere in my code.  It hits a `No such page` error when I try to visit `pages/about` manually.

I noticed about 90% of the submissions didn't have tests/code for Posts.  I think there should be some dummy tests to help students remember to write them.  Something like:
```
it 'writes some tests, or else it gets the hose again'
  expect(true).to eq(false)
end
```
would help remind students.  I personally think it's just muscle memory, not laziness.  "All green, next lesson."

**Comment by bhollan** [comment]
Also, the README's instructions for the User abilities is quite redundant.  If VIPs and Admins can both do the same thing, what's the point of having to roles?

**Comment by bhollan** [comment]
I think VIPs should be able to EDIT and admins can do everything.

**Comment by pletcher** [comment]
1. `pages/about` -- I have no idea why that's being tested. I'm removing it.
2. Agreed on VIPs vs. Admins
3. Also deleted the user delete spec -- not going to allow deleting users (removed it from the README), and I think that test was copied from [some example somewhere](https://github.com/RailsApps/rails_apps_testing/blob/master/lib/generators/testing/configure/templates/spec/devise/features/users/user_delete_spec.rb)
4. Added the dummy spec that you suggested

This lab is a mess. I'm sure I'll fix more things momentarily.
