### ISSUE TITLE
Rspec issues

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/devise_roles_lab#2]
The specs can't access file: `spec/support/helpers/session_helpers.rb` where signin is defined.

Right out of the box, if you run `rspec` you get:

```
Sign in
  user cannot sign in if not registered (FAILED - 1)

Failures:

  1) Sign in user cannot sign in if not registered
     Failure/Error: signin('test@example.com', 'please123')
     
     NoMethodError:
       undefined method `signin' for #<RSpec::ExampleGroups::SignIn:0x007f90393e89f8>
     # ./spec/features/users/sign_in_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.0641 seconds (files took 2.19 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/users/sign_in_spec.rb:11 # Sign in user cannot sign in if not registered
```
I temporarily fixed this issue by moving the logic out of the helpers file and replacing the `signin` method. Starting line sign_in_spec:12:

```
      visit new_user_session_path
      fill_in 'Email', with: 'test@example.com'
      fill_in 'Password', with: 'please123'
      click_button 'Sign in'
```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

With the above code in, sign_in_spec:26:

```
      visit new_user_session_path
      fill_in 'Email', with: user.email
      fill_in 'Password', with: user.password
      click_button 'Log in'
```
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

Ok ALL the tests have the same issue. Just modify them accordingly.
Can use mine as a guide:
 https://github.com/onyoo/devise_roles_lab-v-000/blob/master/spec/features/users/sign_in_spec.rb

PS if you get uninitialized constant for FactoryGirl on the second test, delete your Gemfile.lock and bundle install.

**Comment by AnnJohn** [comment]
thanks @onyoo. Will fix as soon as we can.
