### ISSUE TITLE
undefined method `signin' for #<RSpec::ExampleGroups::SignOut:0x00000006581af0>

### ISSUE THREAD

**Issue by alrawi90** [learn-co-curriculum/devise_roles_lab#22]
Hello ,
This lab has a test bug ,
spec/users/sign_out_spec.rb line number 13 ##>   signin(user.email, user.password)
there is no such a method name for Devise , the correct name is sign_in 
I know that because when change the method call to  ' sign_in(user.email, user.password) ' , it works and the test pass otherwise , I get the error below.
  1) Sign out user signs out successfully
     Failure/Error: signin(user.email, user.password)

     NoMethodError:
       undefined method `signin' for #<RSpec::ExampleGroups::SignOut:0x00000006581af0>
       Did you mean?  sign_in
     # ./spec/features/users/sign_out_spec.rb:13:in `block (2 levels) in <top (required)>'
best ,
Ali Alrawi

**Comment by itzsaga** [comment]
This has been fixed but not closed.
