### ISSUE TITLE
Add more tests to solution as per README

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/devise_roles_lab#23]
The README suggests that the solution should include creating additional specs for the the posts model and posts controller. I struggled with this, only to find that the solution tests are exactly as forked. I have some additional tests in my branch, I'm happy to have those included in the solution (though it doesn't appear I can make a pull request to the solution branch with only that file).

**Comment by sgharms** [comment]
Now part of the solution branch! Thanks
