### ISSUE TITLE
Needs more roles practice

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/devise_roles_lab#24]
I feel like this lab has very little to do with Devise Roles overall. Lots of work in views and partials. Things like creating a nav seem out of place and just busy work. This could be by design but I feel this lab could be revised and offer more practice on roles. The video review even has Avi starting it off saying he really wants to get to the Roles part.

**Comment by itzsaga** [comment]
I just finished the lecture video. Avi definitely finishes the lab talking about how it's 5 minutes of roles code writing and 55 minutes of working with Devise.

**Comment by gj** [comment]
We're currently in the process of tweaking the authentication and authorization section, and this is great feedback.

Thanks @itzsaga !

**Comment by sgharms** [comment]
Added!
