### ISSUE TITLE
user_spec.rb

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/devise_roles_lab#4]
This set of tests checks primarily that the role set returns a certain value. If we look at this example, found on user_spec.rb:18 : 
```
  it "#role can be set to :vip" do
    @user.role = :vip
    expect(@user.role).to eq "vip"
  end
```
we will get the following error:
```
Failures:

  1) User #role can be set to :vip
     Failure/Error: expect(@user.role).to eq :vip
     
       expected: :vip
            got: "vip"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -:vip
       +"vip"
       
     # ./spec/models/user_spec.rb:20:in `block (2 levels) in <top (required)>'
```
To I realize the test passes with the solution, but the only way I could get it to pass was to change line 20 to:
```
    expect(@user.role).to eq "vip"
```

I'd be interested to know how else to not have it return a string.

**Comment by vicfriedman** [comment]
hey @onyoo,

Just submitting a PR to fix this issue, seems like it was a configuration issue. I used your solution to test things, and it seems like you still have an issue with the user logout spec `Sign out user signs out successfully`. Try and take another look once this issue is closed!
