### ISSUE TITLE
Alot of issues with Tests

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/devise_roles_lab#5]
There seem to be alot of issues with tests on this lab. 

As noted on another issue, need to include the sessions_helpers.rb in rails_helpers.rb file

session_helpers.rb file line 15 needs to be changed to 'Log in' rather than 'Sign in' as devise uses the term 'Log in' for the buttons. 

Also sign_out_spec.rb line 16 is causing issues. I have had to comment out this line to get the test to pass.

**Comment by AnnJohn** [comment]
thank you @dannyd4315. We'll fix these within the next month. Sorry about the issues regardless with this and having to do a work-around
