### ISSUE TITLE
Readme wants students to write new specs

### ISSUE THREAD

**Issue by shinyrachel** [learn-co-curriculum/devise_roles_lab#8]
The readme says, after passing all included specs, we should create a Post model with a corresponding controller and views, and write our own specs. The curriculum thus far has never expected students to write our own tests for a lab (nor taught how to do it).

**Comment by pletcher** [comment]
http://rspec.info/

**Comment by pletcher** [comment]
Sorry, I didn't mean to be super terse. I'm going through a lot of issues and trying to close them quickly.

We'll have to find a way to work testing in earlier in the curriculum. The trouble is, it's kind of hard to test testing. I'll give it a think.

Thanks for raising this issue!
